export const Colors = {
  primary:         '#155DFC',
  primaryPressed:  '#1d4ed8',
  gradientStart:   '#155DFC',
  gradientMid:     '#9810FA',
  gradientEnd:     '#F6339A',
  white:           '#FFFFFF',
  errorRed:        '#DC2626',
  errorRedBg:      '#FEF2F2',
  errorRedBorder:  '#FECACA',
  successGreen:    '#16A34A',
  successGreenBg:  '#F0FDF4',
  textPrimary:     '#111827',
  textSecondary:   '#6B7280',
  textMuted:       '#9CA3AF',
  borderDefault:   '#E5E7EB',
  cardBg:          '#FFFFFF',
  pageBg:          '#F8FAFC',
  chatBubbleMe:      '#155DFC',
  chatBubbleMeText:  '#FFFFFF',
  chatBubbleOther:   '#F3F4F6',
  chatBubbleOtherText:'#111827',
  chatSidebarBg:     '#FFFFFF',
  chatHeaderBg:      '#FFFFFF',
  chatInputBg:       '#F9FAFB',
  chatDivider:       '#F3F4F6',
  onlineGreen:       '#34D399',
  unreadBlue:        '#155DFC',
  mentionAmber:      '#F59E0B',
  bannerAmberBg:     '#FFFBEB',
  bannerAmberBorder: '#FDE68A',
  bannerAmberText:   '#92400E',
  bannerRedBg:       '#FEF2F2',
  bannerRedBorder:   '#FECACA',
  bannerRedText:     '#991B1B',
} as const;
