export const Colors = {
  primary:         '#155DFC',
  primaryPressed:  '#1d4ed8',
  gradientStart:   '#155DFC',
  gradientMid:     '#9810FA',
  gradientEnd:     '#F6339A',
  white:           '#FFFFFF',
  errorRed:        '#DC2626',
  errorRedBg:      '#FEF2F2',
  errorRedBorder:  '#FECACA',
  successGreen:    '#16A34A',
  successGreenBg:  '#F0FDF4',
  textPrimary:     '#111827',
  textSecondary:   '#6B7280',
  textMuted:       '#9CA3AF',
  borderDefault:   '#E5E7EB',
  cardBg:          '#FFFFFF',
  pageBg:          '#F8FAFC',
} as const;
